#!/bin/bash

SUPPORTED_COMMITED_FILES=$((git diff --name-only HEAD~ HEAD 2>/dev/null || git diff-tree -r --no-commit-id --name-only --root HEAD) | grep '^\(Gemfile\|Gemfile\.lock\|.*\.gemspec\|package\.json\|npm-shrinkwrap\.json\)$')

if [[ $SUPPORTED_COMMITED_FILES > 0 ]]; then
  gemnasium push
fi
